BEGIN
    FOR t IN (
        SELECT 'MATRICULA_HISTORICA' nombre FROM dual UNION ALL
        SELECT 'PLAN_OFERTA' FROM dual UNION ALL
        SELECT 'OFERTA_ACADEMICA' FROM dual UNION ALL
        SELECT 'CARRERA' FROM dual UNION ALL
        SELECT 'ACREDITACION_INSTITUCION' FROM dual UNION ALL
        SELECT 'INSTITUCION' FROM dual UNION ALL
        SELECT 'COMUNA' FROM dual UNION ALL
        SELECT 'PROVINCIA' FROM dual UNION ALL
        SELECT 'REGION' FROM dual UNION ALL
        SELECT 'TIPO_INSTITUCION' FROM dual UNION ALL
        SELECT 'AREA_CONOCIMIENTO' FROM dual UNION ALL
        SELECT 'NIVEL_CARRERA' FROM dual UNION ALL
        SELECT 'NIVEL_ESTUDIO' FROM dual UNION ALL
        SELECT 'MODALIDAD' FROM dual UNION ALL
        SELECT 'JORNADA' FROM dual UNION ALL
        SELECT 'TIPO_PLAN' FROM dual UNION ALL
        SELECT 'REQUISITO_INGRESO' FROM dual UNION ALL
        SELECT 'VIA_INGRESO' FROM dual UNION ALL
        SELECT 'STAGING_MATRICULA' FROM dual
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE ' || t.nombre || ' CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/
