ALTER TABLE REGION ADD CONSTRAINT pk_region PRIMARY KEY (id_region);
ALTER TABLE REGION ADD CONSTRAINT uq_region_nombre UNIQUE (nombre);

ALTER TABLE PROVINCIA ADD CONSTRAINT pk_provincia PRIMARY KEY (id_provincia);
ALTER TABLE PROVINCIA ADD CONSTRAINT fk_prov_region FOREIGN KEY (id_region) REFERENCES REGION(id_region);
ALTER TABLE PROVINCIA ADD CONSTRAINT uq_prov_region_nom UNIQUE (id_region, nombre);

ALTER TABLE COMUNA ADD CONSTRAINT pk_comuna PRIMARY KEY (id_comuna);
ALTER TABLE COMUNA ADD CONSTRAINT fk_com_prov FOREIGN KEY (id_provincia) REFERENCES PROVINCIA(id_provincia);
ALTER TABLE COMUNA ADD CONSTRAINT uq_com_prov_nom UNIQUE (id_provincia, nombre);

ALTER TABLE TIPO_INSTITUCION ADD CONSTRAINT pk_tipo_inst PRIMARY KEY (id_tipo_institucion);
ALTER TABLE TIPO_INSTITUCION ADD CONSTRAINT uq_tipo_inst_nom UNIQUE (nombre);

ALTER TABLE INSTITUCION ADD CONSTRAINT pk_institucion PRIMARY KEY (id_institucion);
ALTER TABLE INSTITUCION ADD CONSTRAINT fk_inst_tipo FOREIGN KEY (id_tipo_institucion) REFERENCES TIPO_INSTITUCION(id_tipo_institucion);
ALTER TABLE INSTITUCION ADD CONSTRAINT uq_inst_nombre UNIQUE (nombre);

ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT pk_acred_inst PRIMARY KEY (id_acreditacion);
ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT fk_acred_inst FOREIGN KEY (id_institucion) REFERENCES INSTITUCION(id_institucion);
ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT uq_acred_inst_anio UNIQUE (id_institucion, anio_referencia);
ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT ck_acred_estado CHECK (estado IN ('ACREDITADA', 'NO ACREDITADA'));
ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT ck_acred_anio CHECK (anio_referencia BETWEEN 2000 AND 2100);
ALTER TABLE ACREDITACION_INSTITUCION ADD CONSTRAINT ck_acred_anios CHECK (anios_acreditacion IS NULL OR anios_acreditacion BETWEEN 1 AND 10);

ALTER TABLE AREA_CONOCIMIENTO ADD CONSTRAINT pk_area PRIMARY KEY (id_area);
ALTER TABLE AREA_CONOCIMIENTO ADD CONSTRAINT uq_area_nombre UNIQUE (nombre);

ALTER TABLE NIVEL_ESTUDIO ADD CONSTRAINT pk_nivel_est PRIMARY KEY (id_nivel_estudio);
ALTER TABLE NIVEL_ESTUDIO ADD CONSTRAINT uq_nivel_est_nom UNIQUE (nombre);

ALTER TABLE NIVEL_CARRERA ADD CONSTRAINT pk_nivel_carr PRIMARY KEY (id_nivel_carrera);
ALTER TABLE NIVEL_CARRERA ADD CONSTRAINT fk_nc_ne FOREIGN KEY (id_nivel_estudio) REFERENCES NIVEL_ESTUDIO(id_nivel_estudio);
ALTER TABLE NIVEL_CARRERA ADD CONSTRAINT uq_nivel_carr_nom UNIQUE (nombre);

ALTER TABLE MODALIDAD ADD CONSTRAINT pk_modalidad PRIMARY KEY (id_modalidad);
ALTER TABLE MODALIDAD ADD CONSTRAINT uq_modalidad_nom UNIQUE (nombre);

ALTER TABLE JORNADA ADD CONSTRAINT pk_jornada PRIMARY KEY (id_jornada);
ALTER TABLE JORNADA ADD CONSTRAINT uq_jornada_nom UNIQUE (nombre);

ALTER TABLE CARRERA ADD CONSTRAINT pk_carrera PRIMARY KEY (id_carrera);
ALTER TABLE CARRERA ADD CONSTRAINT fk_carrera_area FOREIGN KEY (id_area) REFERENCES AREA_CONOCIMIENTO(id_area);
ALTER TABLE CARRERA ADD CONSTRAINT fk_carrera_nivel FOREIGN KEY (id_nivel_carrera) REFERENCES NIVEL_CARRERA(id_nivel_carrera);
ALTER TABLE CARRERA ADD CONSTRAINT uq_carrera_nom_niv UNIQUE (nombre, id_nivel_carrera);

ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT pk_oferta PRIMARY KEY (id_oferta);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT fk_of_inst FOREIGN KEY (id_institucion) REFERENCES INSTITUCION(id_institucion);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT fk_of_carrera FOREIGN KEY (id_carrera) REFERENCES CARRERA(id_carrera);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT fk_of_comuna FOREIGN KEY (id_comuna) REFERENCES COMUNA(id_comuna);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT fk_of_modalidad FOREIGN KEY (id_modalidad) REFERENCES MODALIDAD(id_modalidad);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT fk_of_jornada FOREIGN KEY (id_jornada) REFERENCES JORNADA(id_jornada);
ALTER TABLE OFERTA_ACADEMICA ADD CONSTRAINT uq_oferta_logica UNIQUE (id_institucion, id_carrera, id_comuna, id_modalidad, id_jornada);

ALTER TABLE TIPO_PLAN ADD CONSTRAINT pk_tipo_plan PRIMARY KEY (id_tipo_plan);
ALTER TABLE TIPO_PLAN ADD CONSTRAINT uq_tipo_plan_nom UNIQUE (nombre);

ALTER TABLE PLAN_OFERTA ADD CONSTRAINT pk_plan_oferta PRIMARY KEY (id_plan_oferta);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT fk_plan_oferta FOREIGN KEY (id_oferta) REFERENCES OFERTA_ACADEMICA(id_oferta);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT fk_plan_tipo FOREIGN KEY (id_tipo_plan) REFERENCES TIPO_PLAN(id_tipo_plan);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT uq_plan_oferta UNIQUE (id_oferta, id_tipo_plan, duracion_plan, duracion_titulacion, duracion_total, valor_matricula, valor_arancel);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT ck_plan_duracion CHECK (duracion_plan > 0 AND duracion_plan <= 30);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT ck_tit_duracion CHECK (duracion_titulacion >= 0 AND duracion_titulacion <= 30);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT ck_total_duracion CHECK (duracion_total > 0 AND duracion_total <= 30);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT ck_val_matricula CHECK (valor_matricula >= 0);
ALTER TABLE PLAN_OFERTA ADD CONSTRAINT ck_val_arancel CHECK (valor_arancel >= 0);

ALTER TABLE REQUISITO_INGRESO ADD CONSTRAINT pk_req_ing PRIMARY KEY (id_requisito_ingreso);
ALTER TABLE REQUISITO_INGRESO ADD CONSTRAINT uq_req_ing_nom UNIQUE (nombre);

ALTER TABLE VIA_INGRESO ADD CONSTRAINT pk_via_ing PRIMARY KEY (id_via_ingreso);
ALTER TABLE VIA_INGRESO ADD CONSTRAINT uq_via_ing_nom UNIQUE (nombre);

ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT pk_mat_hist PRIMARY KEY (id_matricula);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT uq_mat_fuente UNIQUE (id_registro_fuente);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT fk_mat_plan FOREIGN KEY (id_plan_oferta) REFERENCES PLAN_OFERTA(id_plan_oferta);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT fk_mat_req FOREIGN KEY (id_requisito_ingreso) REFERENCES REQUISITO_INGRESO(id_requisito_ingreso);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT fk_mat_via FOREIGN KEY (id_via_ingreso) REFERENCES VIA_INGRESO(id_via_ingreso);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT ck_mat_genero CHECK (genero IN ('Femenino', 'Masculino'));
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT ck_mat_edad CHECK (edad BETWEEN 14 AND 120);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT ck_mat_anio CHECK (anio_ingreso BETWEEN 1900 AND 2100);
ALTER TABLE MATRICULA_HISTORICA ADD CONSTRAINT ck_mat_sem CHECK (semestre_ingreso IN ('Primer semestre', 'Segundo semestre'));
