SELECT 'REGION' tabla, COUNT(*) cantidad FROM REGION
UNION ALL SELECT 'PROVINCIA', COUNT(*) FROM PROVINCIA
UNION ALL SELECT 'COMUNA', COUNT(*) FROM COMUNA
UNION ALL SELECT 'TIPO_INSTITUCION', COUNT(*) FROM TIPO_INSTITUCION
UNION ALL SELECT 'INSTITUCION', COUNT(*) FROM INSTITUCION
UNION ALL SELECT 'ACREDITACION_INSTITUCION', COUNT(*) FROM ACREDITACION_INSTITUCION
UNION ALL SELECT 'AREA_CONOCIMIENTO', COUNT(*) FROM AREA_CONOCIMIENTO
UNION ALL SELECT 'NIVEL_ESTUDIO', COUNT(*) FROM NIVEL_ESTUDIO
UNION ALL SELECT 'NIVEL_CARRERA', COUNT(*) FROM NIVEL_CARRERA
UNION ALL SELECT 'MODALIDAD', COUNT(*) FROM MODALIDAD
UNION ALL SELECT 'JORNADA', COUNT(*) FROM JORNADA
UNION ALL SELECT 'CARRERA', COUNT(*) FROM CARRERA
UNION ALL SELECT 'OFERTA_ACADEMICA', COUNT(*) FROM OFERTA_ACADEMICA
UNION ALL SELECT 'TIPO_PLAN', COUNT(*) FROM TIPO_PLAN
UNION ALL SELECT 'PLAN_OFERTA', COUNT(*) FROM PLAN_OFERTA
UNION ALL SELECT 'REQUISITO_INGRESO', COUNT(*) FROM REQUISITO_INGRESO
UNION ALL SELECT 'VIA_INGRESO', COUNT(*) FROM VIA_INGRESO
UNION ALL SELECT 'MATRICULA_HISTORICA', COUNT(*) FROM MATRICULA_HISTORICA;

SELECT COUNT(*) AS matriculas_cargadas
FROM MATRICULA_HISTORICA;

SELECT id_registro_fuente, COUNT(*) AS cantidad
FROM MATRICULA_HISTORICA
GROUP BY id_registro_fuente
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS costos_negativos
FROM PLAN_OFERTA
WHERE valor_matricula < 0 OR valor_arancel < 0;

SELECT COUNT(*) AS oferta_sin_institucion
FROM OFERTA_ACADEMICA o
LEFT JOIN INSTITUCION i ON i.id_institucion = o.id_institucion
WHERE i.id_institucion IS NULL;

SELECT COUNT(*) AS oferta_sin_carrera
FROM OFERTA_ACADEMICA o
LEFT JOIN CARRERA c ON c.id_carrera = o.id_carrera
WHERE c.id_carrera IS NULL;

SELECT COUNT(*) AS oferta_sin_comuna
FROM OFERTA_ACADEMICA o
LEFT JOIN COMUNA c ON c.id_comuna = o.id_comuna
WHERE c.id_comuna IS NULL;

SELECT COUNT(*) AS plan_sin_oferta
FROM PLAN_OFERTA p
LEFT JOIN OFERTA_ACADEMICA o ON o.id_oferta = p.id_oferta
WHERE o.id_oferta IS NULL;

SELECT COUNT(*) AS matricula_sin_plan
FROM MATRICULA_HISTORICA m
LEFT JOIN PLAN_OFERTA p ON p.id_plan_oferta = m.id_plan_oferta
WHERE p.id_plan_oferta IS NULL;

SELECT COUNT(*) AS matricula_sin_requisito
FROM MATRICULA_HISTORICA m
LEFT JOIN REQUISITO_INGRESO r ON r.id_requisito_ingreso = m.id_requisito_ingreso
WHERE r.id_requisito_ingreso IS NULL;

SELECT COUNT(*) AS matricula_sin_via
FROM MATRICULA_HISTORICA m
LEFT JOIN VIA_INGRESO v ON v.id_via_ingreso = m.id_via_ingreso
WHERE v.id_via_ingreso IS NULL;

SELECT id_institucion, id_carrera, id_comuna, id_modalidad, id_jornada, COUNT(*) AS cantidad
FROM OFERTA_ACADEMICA
GROUP BY id_institucion, id_carrera, id_comuna, id_modalidad, id_jornada
HAVING COUNT(*) > 1;

SELECT nombre, id_nivel_carrera, COUNT(*) AS cantidad
FROM CARRERA
GROUP BY nombre, id_nivel_carrera
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS carreras_sin_area
FROM CARRERA c
LEFT JOIN AREA_CONOCIMIENTO a ON a.id_area = c.id_area
WHERE a.id_area IS NULL;

SELECT COUNT(*) AS niveles_sin_nivel_estudio
FROM NIVEL_CARRERA nc
LEFT JOIN NIVEL_ESTUDIO ne ON ne.id_nivel_estudio = nc.id_nivel_estudio
WHERE ne.id_nivel_estudio IS NULL;
